CREATE TABLE notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  modified_date DATE DEFAULT now(),
  -- folders INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL,
  note_name TEXT,
  note_content TEXT
);